#!/usr/bin/env bash
# Configure the OpenSearch security plugin on the server. Idempotent — safe to
# rerun. Generates passwords on first run, then provisions:
#
#   * /etc/feedback-search/admin.env   (OPENSEARCH_INITIAL_ADMIN_PASSWORD)
#   * /etc/feedback-search/secrets.env (admin / proxy / ingest passwords)
#   * /etc/feedback-search/ingest.env  (OPENSEARCH_USER, OPENSEARCH_PASSWORD,
#                                       OPENSEARCH_URL — sourced by systemd)
#   * /etc/nginx/conf.d/feedback-search-upstream-auth.inc
#                                      (proxy_set_header Authorization Basic …)


set -euo pipefail

SECRETS_DIR="${SECRETS_DIR:-/etc/feedback-search}"
ADMIN_ENV="${SECRETS_DIR}/admin.env"
SECRETS_ENV="${SECRETS_DIR}/secrets.env"
INGEST_ENV="${SECRETS_DIR}/ingest.env"
NGINX_AUTH_INC="${NGINX_AUTH_INC:-/etc/nginx/conf.d/feedback-search-upstream-auth.inc}"
OS_URL="${OPENSEARCH_URL:-http://127.0.0.1:9200}"
OS_INDEX_ALIAS="${OPENSEARCH_ALIAS:-feedback-posts}"
OS_BACKING_PATTERN="${OPENSEARCH_BACKING_PATTERN:-feedback-posts-*}"

PROXY_USER="${PROXY_USER:-feedback-search}"
INGEST_USER="${INGEST_USER:-feedback-ingest}"

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "Run as root." >&2
    exit 1
  fi
}

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1" >&2; exit 1; }
}

random_password() {
  # 32 URL-safe characters; avoids shell-quoting trouble in env files.
  openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-32
}

ensure_dirs() {
  install -d -m 0700 -o root -g root "${SECRETS_DIR}"
}

ensure_secrets() {
  if [[ -s "${SECRETS_ENV}" ]]; then
    # shellcheck disable=SC1090
    . "${SECRETS_ENV}"
  fi
  : "${ADMIN_PASSWORD:=$(random_password)}"
  : "${PROXY_PASSWORD:=$(random_password)}"
  : "${INGEST_PASSWORD:=$(random_password)}"

  install -m 0600 -o root -g root /dev/null "${SECRETS_ENV}"
  cat >"${SECRETS_ENV}" <<EOF
# Auto-generated by bootstrap_security.sh. Do not edit by hand. To rotate any
# password, delete the relevant line and rerun this script.
ADMIN_PASSWORD=${ADMIN_PASSWORD}
PROXY_PASSWORD=${PROXY_PASSWORD}
INGEST_PASSWORD=${INGEST_PASSWORD}
EOF

  install -m 0600 -o root -g root /dev/null "${ADMIN_ENV}"
  cat >"${ADMIN_ENV}" <<EOF
OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

  install -m 0600 -o root -g root /dev/null "${INGEST_ENV}"
  cat >"${INGEST_ENV}" <<EOF
FEEDBACK_REPO_ROOT=${FEEDBACK_REPO_ROOT:-/srv/feedback.vrchat.com}
OPENSEARCH_URL=${OS_URL}
OPENSEARCH_USER=${INGEST_USER}
OPENSEARCH_PASSWORD=${INGEST_PASSWORD}
FORCE_REINDEX=0
EOF

  export ADMIN_PASSWORD PROXY_PASSWORD INGEST_PASSWORD
}

wait_for_opensearch() {
  local attempt
  for attempt in $(seq 1 120); do
    if curl -fsS -m 5 -u "admin:${ADMIN_PASSWORD}" "${OS_URL}/_cluster/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "OpenSearch did not become reachable on ${OS_URL} as admin within 4 minutes." >&2
  exit 1
}

os_put() {
  local path="$1"
  local body="$2"
  local code
  code=$(curl -sS -o /tmp/_os_put_resp.$$ -w "%{http_code}" \
    -u "admin:${ADMIN_PASSWORD}" \
    -H 'Content-Type: application/json' \
    -X PUT "${OS_URL}${path}" --data-binary "${body}")
  if [[ "${code}" != "200" && "${code}" != "201" ]]; then
    echo "PUT ${path} -> HTTP ${code}" >&2
    cat /tmp/_os_put_resp.$$ >&2
    rm -f /tmp/_os_put_resp.$$
    exit 1
  fi
  rm -f /tmp/_os_put_resp.$$
}

provision_security() {
  os_put "/_plugins/_security/api/internalusers/${PROXY_USER}" "$(cat <<JSON
{
  "password": "${PROXY_PASSWORD}",
  "backend_roles": [],
  "description": "Read-only public proxy user (nginx attaches Basic auth)."
}
JSON
)"
  os_put "/_plugins/_security/api/internalusers/${INGEST_USER}" "$(cat <<JSON
{
  "password": "${INGEST_PASSWORD}",
  "backend_roles": [],
  "description": "Bulk ingest user (opensearch_bulk.py)."
}
JSON
)"

  # Read-only role: search/get/mapping against the alias only. No cluster
  # permissions besides the cluster-health probe powering /health.
  os_put "/_plugins/_security/api/roles/${PROXY_USER}-readonly" "$(cat <<JSON
{
  "cluster_permissions": [
    "cluster:monitor/health"
  ],
  "index_permissions": [
    {
      "index_patterns": ["${OS_INDEX_ALIAS}"],
      "allowed_actions": [
        "read",
        "indices:admin/mappings/get"
      ]
    }
  ],
  "tenant_permissions": []
}
JSON
)"

  # Ingest role: full CRUD on backing indices, alias swap on the cluster.
  os_put "/_plugins/_security/api/roles/${INGEST_USER}-rw" "$(cat <<JSON
{
  "cluster_permissions": [
    "cluster:monitor/health",
    "cluster:monitor/state",
    "cluster_composite_ops",
    "indices:admin/aliases",
    "indices:admin/aliases/get"
  ],
  "index_permissions": [
    {
      "index_patterns": ["${OS_INDEX_ALIAS}", "${OS_BACKING_PATTERN}"],
      "allowed_actions": ["indices_all"]
    }
  ],
  "tenant_permissions": []
}
JSON
)"

  os_put "/_plugins/_security/api/rolesmapping/${PROXY_USER}-readonly" "$(cat <<JSON
{
  "users": ["${PROXY_USER}"],
  "backend_roles": [],
  "hosts": []
}
JSON
)"

  os_put "/_plugins/_security/api/rolesmapping/${INGEST_USER}-rw" "$(cat <<JSON
{
  "users": ["${INGEST_USER}"],
  "backend_roles": [],
  "hosts": []
}
JSON
)"
}

write_nginx_auth_include() {
  install -d -m 0755 /etc/nginx/conf.d
  local b64
  b64=$(printf '%s:%s' "${PROXY_USER}" "${PROXY_PASSWORD}" | base64 | tr -d '\n')
  install -m 0640 -o root -g www-data /dev/null "${NGINX_AUTH_INC}" 2>/dev/null \
    || install -m 0644 -o root -g root /dev/null "${NGINX_AUTH_INC}"
  cat >"${NGINX_AUTH_INC}" <<EOF
# Generated by deploy/scripts/bootstrap_security.sh. Do not edit by hand.
# nginx attaches this Authorization header to every upstream OpenSearch call.
# The public client never sees the credential.
proxy_set_header Authorization "Basic ${b64}";
EOF
  if command -v nginx >/dev/null 2>&1; then
    if nginx -t >/dev/null 2>&1; then
      systemctl reload nginx
    else
      echo "nginx -t failed; not reloading. Run \`nginx -t\` to inspect." >&2
    fi
  fi
}

apply_cluster_settings() {
  curl -fsS -u "admin:${ADMIN_PASSWORD}" \
    -H 'Content-Type: application/json' \
    -X PUT "${OS_URL}/_cluster/settings" --data-binary "$(cat <<'JSON'
{
  "persistent": {
    "search.max_buckets": 10000,
    "search.max_open_scroll_context": 0,
    "indices.query.bool.max_clause_count": 1024
  }
}
JSON
)" >/dev/null
}

main() {
  require_root
  need openssl
  need curl
  need base64

  ensure_dirs
  local FIRST_RUN=0
  if [[ ! -s "${SECRETS_ENV}" ]]; then
    FIRST_RUN=1
  fi
  ensure_secrets

  if [[ "${FIRST_RUN}" -eq 1 ]]; then
    echo "[bootstrap-security] first-run secrets generated; restarting opensearch container so OPENSEARCH_INITIAL_ADMIN_PASSWORD takes effect" >&2
    if [[ -n "${FEEDBACK_REPO_ROOT:-}" && -f "${FEEDBACK_REPO_ROOT}/deploy/docker-compose.yml" ]]; then
      docker compose -f "${FEEDBACK_REPO_ROOT}/deploy/docker-compose.yml" up -d --force-recreate opensearch
    fi
  fi

  wait_for_opensearch
  provision_security
  apply_cluster_settings
  write_nginx_auth_include
  echo "[bootstrap-security] done. proxy user=${PROXY_USER}, ingest user=${INGEST_USER}." >&2
}

main "$@"
