#!/usr/bin/env bash
# Configures OpenSearch Security on the indexer host (idempotent).
# Writes machine-local credential bundles under /etc/feedback-search/.
#
# Outputs:
#   admin.env           — bootstrap password for OPENSEARCH_INITIAL_ADMIN_PASSWORD (Docker)
#   secrets.env        — ADMIN_PASSWORD, PROXY_PASSWORD, INGEST_PASSWORD (ROTATE by deleting keys)
#   ingest.env          — systemd feedback-ingest: bulk-write user + repo root
#   gateway.env         — systemd feedback-search-gateway: read-only user → OpenSearch
#
# secrets.env uses PROXY_* for the read-only gateway OpenSearch identity
# (${PROXY_USER} / gateway.env); INGEST_* is the bulk indexer.


set -euo pipefail

SECRETS_DIR="${SECRETS_DIR:-/etc/feedback-search}"
ADMIN_ENV="${SECRETS_DIR}/admin.env"
SECRETS_ENV="${SECRETS_DIR}/secrets.env"
INGEST_ENV="${SECRETS_DIR}/ingest.env"
OS_URL="${OPENSEARCH_URL:-http://127.0.0.1:9200}"
OS_INDEX_ALIAS="${OPENSEARCH_ALIAS:-feedback-posts}"
OS_BACKING_PATTERN="${OPENSEARCH_BACKING_PATTERN:-feedback-posts-*}"
# Internal OpenSearch identities (PROXY_* = read alias; INGEST_* = bulk + aliases)
PROXY_USER="${PROXY_USER:-feedback-search}"
INGEST_USER="${INGEST_USER:-feedback-ingest}"

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "Run as root." >&2
    exit 1
  fi
}

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1" >&2; exit 1; }
}

random_password() {
  openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-32
}

ensure_dirs() {
  install -d -m 0700 -o root -g root "${SECRETS_DIR}"
}

ensure_secrets() {
  if [[ -s "${SECRETS_ENV}" ]]; then
    # shellcheck disable=SC1090
    . "${SECRETS_ENV}"
  fi
  : "${ADMIN_PASSWORD:=$(random_password)}"
  : "${PROXY_PASSWORD:=$(random_password)}"
  : "${INGEST_PASSWORD:=$(random_password)}"

  install -m 0600 -o root -g root /dev/null "${SECRETS_ENV}"
  cat >"${SECRETS_ENV}" <<EOF
# Auto-generated by deploy/scripts/bootstrap_security.sh
# Rotate: delete a password line below and rerun this script on the host.
ADMIN_PASSWORD=${ADMIN_PASSWORD}
PROXY_PASSWORD=${PROXY_PASSWORD}
INGEST_PASSWORD=${INGEST_PASSWORD}
EOF

  install -m 0600 -o root -g root /dev/null "${ADMIN_ENV}"
  cat >"${ADMIN_ENV}" <<EOF
OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

  install -m 0600 -o root -g root /dev/null "${INGEST_ENV}"
  cat >"${INGEST_ENV}" <<EOF
FEEDBACK_REPO_ROOT=${FEEDBACK_REPO_ROOT}
OPENSEARCH_URL=${OS_URL}
OPENSEARCH_USER=${INGEST_USER}
OPENSEARCH_PASSWORD=${INGEST_PASSWORD}
FORCE_REINDEX=0
EOF

  export ADMIN_PASSWORD PROXY_PASSWORD INGEST_PASSWORD
}

wait_for_opensearch() {
  local attempt
  for attempt in $(seq 1 120); do
    if curl -fsS -m 5 -u "admin:${ADMIN_PASSWORD}" "${OS_URL}/_cluster/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "OpenSearch did not become reachable on ${OS_URL} as admin within 4 minutes." >&2
  exit 1
}

os_put() {
  local path="$1"
  local body="$2"
  local code
  code=$(curl -sS -o /tmp/_os_put_resp.$$ -w "%{http_code}" \
    -u "admin:${ADMIN_PASSWORD}" \
    -H 'Content-Type: application/json' \
    -X PUT "${OS_URL}${path}" --data-binary "${body}")
  if [[ "${code}" != "200" && "${code}" != "201" ]]; then
    echo "PUT ${path} -> HTTP ${code}" >&2
    cat /tmp/_os_put_resp.$$ >&2
    rm -f /tmp/_os_put_resp.$$
    exit 1
  fi
  rm -f /tmp/_os_put_resp.$$
}

provision_security() {
  os_put "/_plugins/_security/api/internalusers/${PROXY_USER}" "$(cat <<JSON
{
  "password": "${PROXY_PASSWORD}",
  "backend_roles": [],
  "description": "Read-only gateway identity (alias ${OS_INDEX_ALIAS})."
}
JSON
)"
  os_put "/_plugins/_security/api/internalusers/${INGEST_USER}" "$(cat <<JSON
{
  "password": "${INGEST_PASSWORD}",
  "backend_roles": [],
  "description": "Bulk indexer (alias swap / backing lifecycle)."
}
JSON
)"

  # Gateway: reads the published alias plus mapping metadata required by SearchKit.
  os_put "/_plugins/_security/api/roles/${PROXY_USER}-readonly" "$(cat <<JSON
{
  "cluster_permissions": [
    "cluster:monitor/health"
  ],
  "index_permissions": [
    {
      "index_patterns": ["${OS_INDEX_ALIAS}"],
      "allowed_actions": [
        "read",
        "indices:admin/mappings/get"
      ]
    }
  ],
  "tenant_permissions": []
}
JSON
)"

  os_put "/_plugins/_security/api/roles/${INGEST_USER}-rw" "$(cat <<JSON
{
  "cluster_permissions": [
    "cluster:monitor/health",
    "cluster:monitor/state",
    "cluster_composite_ops",
    "indices:admin/aliases",
    "indices:admin/aliases/get"
  ],
  "index_permissions": [
    {
      "index_patterns": ["${OS_INDEX_ALIAS}", "${OS_BACKING_PATTERN}"],
      "allowed_actions": ["indices_all"]
    }
  ],
  "tenant_permissions": []
}
JSON
)"

  os_put "/_plugins/_security/api/rolesmapping/${PROXY_USER}-readonly" "$(cat <<JSON
{
  "users": ["${PROXY_USER}"],
  "backend_roles": [],
  "hosts": []
}
JSON
)"

  os_put "/_plugins/_security/api/rolesmapping/${INGEST_USER}-rw" "$(cat <<JSON
{
  "users": ["${INGEST_USER}"],
  "backend_roles": [],
  "hosts": []
}
JSON
)"
}

write_gateway_env() {
  local gateway_env="${SECRETS_DIR}/gateway.env"
  install -m 0600 -o root -g root /dev/null "${gateway_env}"
  cat >"${gateway_env}" <<EOF
# Generated by deploy/scripts/bootstrap_security.sh — systemd EnvironmentFile
OPENSEARCH_URL=${OS_URL}
OPENSEARCH_USER=${PROXY_USER}
OPENSEARCH_PASSWORD=${PROXY_PASSWORD}
GATEWAY_BIND=127.0.0.1
PORT=3333
EOF
}

apply_cluster_settings() {
  curl -fsS -u "admin:${ADMIN_PASSWORD}" \
    -H 'Content-Type: application/json' \
    -X PUT "${OS_URL}/_cluster/settings" --data-binary "$(cat <<'JSON'
{
  "persistent": {
    "search.max_buckets": 10000,
    "search.max_open_scroll_context": 0,
    "indices.query.bool.max_clause_count": 1024
  }
}
JSON
)" >/dev/null
}

main() {
  require_root
  need openssl
  need curl
  : "${FEEDBACK_REPO_ROOT:?FEEDBACK_REPO_ROOT must be set}"

  ensure_dirs
  local FIRST_RUN=0
  if [[ ! -s "${SECRETS_ENV}" ]]; then
    FIRST_RUN=1
  fi
  ensure_secrets

  if [[ "${FIRST_RUN}" -eq 1 ]]; then
    echo "[bootstrap_security] Generated new secrets — recreating OpenSearch container so admin password activates." >&2
    if [[ -f "${FEEDBACK_REPO_ROOT}/deploy/docker-compose.yml" ]]; then
      docker compose -f "${FEEDBACK_REPO_ROOT}/deploy/docker-compose.yml" up -d --force-recreate opensearch
    fi
  fi

  wait_for_opensearch
  provision_security
  apply_cluster_settings
  write_gateway_env

  echo "[bootstrap_security] Complete — gateway_os_user=${PROXY_USER} ingest_user=${INGEST_USER}" >&2
}

main "$@"
