#!/usr/bin/env bash
# Enable Cloudflare Authenticated Origin Pulls (AOP) for one hostname.
#
# Run ONCE on the OpenSearch host as root, after:
#   1. The Cloudflare DNS record is proxied (orange cloud).
#   2. nginx is serving HTTPS for the hostname.
#   3. CF_API_TOKEN has Zone:SSL and Certificates:Edit on the zone.
#
# Idempotent. Re-run after CF rotates the AOP CA cert.
#
# Env:
#   CF_API_TOKEN     — must include Zone:SSL and Certificates:Edit
#   ZONE_NAME        — default hackebein.dev
#   RECORD_NAME      — default vrchat-canny  (FQDN = ${RECORD_NAME}.${ZONE_NAME})
#   AOP_CA_OUT       — default /etc/ssl/cloudflare/aop-ca.pem
#   NGINX_AOP_CONF   — default /etc/nginx/conf.d/cloudflare-aop.conf

set -euo pipefail

CF_API_TOKEN="${CF_API_TOKEN:?Set CF_API_TOKEN with Zone:SSL and Certificates:Edit}"
ZONE_NAME="${ZONE_NAME:-hackebein.dev}"
RECORD_NAME="${RECORD_NAME:-vrchat-canny}"
FQDN="${RECORD_NAME}.${ZONE_NAME}"
AOP_CA_OUT="${AOP_CA_OUT:-/etc/ssl/cloudflare/aop-ca.pem}"
NGINX_AOP_CONF="${NGINX_AOP_CONF:-/etc/nginx/conf.d/cloudflare-aop.conf}"
CF_AOP_CA_URL="${CF_AOP_CA_URL:-https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1" >&2; exit 1; }; }
need curl
need jq

ZONE_JSON="$(curl -fsS -H "Authorization: Bearer ${CF_API_TOKEN}" \
  "https://api.cloudflare.com/client/v4/zones?name=${ZONE_NAME}")"
ZONE_ID="$(echo "${ZONE_JSON}" | jq -r '.result[0].id // empty')"
if [[ -z "${ZONE_ID}" ]]; then
  echo "Zone not found: ${ZONE_NAME}" >&2
  exit 1
fi

echo "[aop] Enabling per-hostname AOP for ${FQDN} on zone ${ZONE_ID}…" >&2
PUT_BODY="$(jq -nc --arg h "${FQDN}" '{config:[{hostname:$h, cert_id:"", enabled:true}]}')"
RES="$(curl -fsS -X PUT \
  -H "Authorization: Bearer ${CF_API_TOKEN}" \
  -H "Content-Type: application/json" \
  --data-binary "${PUT_BODY}" \
  "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/origin_tls_client_auth/hostnames")"
if [[ "$(echo "${RES}" | jq -r '.success')" != "true" ]]; then
  echo "[aop] PUT origin_tls_client_auth/hostnames failed:" >&2
  echo "${RES}" | jq . >&2
  exit 1
fi

install -d -m 0755 "$(dirname "${AOP_CA_OUT}")"
echo "[aop] Downloading Cloudflare AOP CA cert from ${CF_AOP_CA_URL}…" >&2
TMP_CA="$(mktemp)"
trap 'rm -f "${TMP_CA}"' EXIT
curl -fsS -o "${TMP_CA}" "${CF_AOP_CA_URL}"
if ! grep -q 'BEGIN CERTIFICATE' "${TMP_CA}"; then
  echo "[aop] Unexpected CA file content; aborting." >&2
  exit 1
fi
install -m 0644 -o root -g root "${TMP_CA}" "${AOP_CA_OUT}"

# Loaded at http{} scope by the default include /etc/nginx/conf.d/*.conf;
# Applies to every server{} in nginx — fine because the OpenSearch host has
# only one HTTPS vhost. nginx's default rejection on missing/invalid client
# cert is `400 No required SSL certificate was sent` — that's the desired
# failure mode for non-Cloudflare TLS.
cat > "${NGINX_AOP_CONF}" <<NGINX
# Generated by deploy/scripts/cloudflare_enable_aop.sh on $(date -u +%FT%TZ).
ssl_client_certificate ${AOP_CA_OUT};
ssl_verify_client on;
ssl_verify_depth 2;
NGINX

if command -v nginx >/dev/null 2>&1; then
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx
    echo "[aop] nginx reloaded; non-Cloudflare TLS handshakes will now fail at the cert step." >&2
  else
    echo "[aop] nginx -t failed; rolling back ${NGINX_AOP_CONF}." >&2
    rm -f "${NGINX_AOP_CONF}"
    exit 1
  fi
fi

echo "[aop] AOP enabled for ${FQDN}. To disable: rm ${NGINX_AOP_CONF} && systemctl reload nginx, then PUT enabled=false via API." >&2
