#!/usr/bin/env bash
# Generate /etc/nginx/conf.d/cloudflare-real-ip.conf so nginx maps each
# Cloudflare edge IP to the real client IP from the CF-Connecting-IP header.
# Pulls the live IP lists from cloudflare.com (unauthenticated). Idempotent.
#
# Without this, every limit_req / limit_conn / X-Forwarded-For / access log
# entry sees the Cloudflare edge IP, not the real client.

set -euo pipefail

OUT="${1:-/etc/nginx/conf.d/cloudflare-real-ip.conf}"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi

fetch() {
  curl -fsS -m 10 --retry 3 --retry-delay 2 "$1"
}

CF_V4="$(fetch https://www.cloudflare.com/ips-v4)"
CF_V6="$(fetch https://www.cloudflare.com/ips-v6)"

if [[ -z "${CF_V4// }" || -z "${CF_V6// }" ]]; then
  echo "Empty Cloudflare IP list response — refusing to overwrite ${OUT}." >&2
  exit 1
fi

{
  echo "# Generated by deploy/scripts/install_cloudflare_real_ip.sh on $(date -u +%FT%TZ)."
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6 — pulled live."
  echo "# Without this, limit_req / limit_conn rate-limit the Cloudflare edge,"
  echo "# not actual clients."
  while IFS= read -r cidr; do
    [[ -z "${cidr}" ]] && continue
    echo "set_real_ip_from ${cidr};"
  done <<< "${CF_V4}"
  while IFS= read -r cidr; do
    [[ -z "${cidr}" ]] && continue
    echo "set_real_ip_from ${cidr};"
  done <<< "${CF_V6}"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "${TMP}"

if [[ -f "${OUT}" ]] && cmp -s "${TMP}" "${OUT}"; then
  exit 0
fi

install -m 0644 -o root -g root "${TMP}" "${OUT}"

if command -v nginx >/dev/null 2>&1 && [[ -f /etc/nginx/nginx.conf ]]; then
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx
  else
    echo "[install_cloudflare_real_ip] nginx -t failed; not reloading. Inspect manually." >&2
    exit 1
  fi
fi
